version: "3.9"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - mongodb+srv://chrisladlu1001:chicken%40%2315@userauth.zohbh8t.mongodb.net/?retryWrites=true&w=majority&appName=userauth
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
